### PR TITLE
Remove OrderedHash

### PR DESCRIPTION
**Pull request by mvz**
Ruby's hashes have been ordered since 1.9.1, so there's no need to have a separate OrderedHash implementation anymore.

### CODE REVIEW

**Comment by mvz** [comment]
Hi @aquasync, any chance you could take a look at this pull request?

**Comment by aquasync** [comment]
Hi @mvz, I'm all for deleting unnecessary code, but at least for the time being 1.8 (old as it may be) is actually the version the library was built using and I've never really got round to making sure it supports 1.9+ properly. One of these days I'll get around to it but time has been hard to come by.

Would be fine with a conditional that only falls back to OrderedHash for RUBY_VERSION < 1.9 though.

**Comment by mvz** [comment]
> I've never really got round to making sure it supports 1.9+ properly.

I'm sure it works fine on newer Rubies. I can add an explicit dependency on 1.9+ to the gemfile to avoid problems for any users of 1.8.

**Comment by mvz** [comment]
Thanks! :tada:

**Pull request merged**
